### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by jake74** [Wanchai/FTPbucket#21]
I got a few failed BitBucket webhook pushes, failing with a 403. 

Seems the IPs in the allow list need updating, see https://bitbucket.org/site/master/issues/7439/git-post-commit-hook-payloads-has-empty

Hope this helps anyone having issues.

**Comment by Wanchai** [comment]
Sorry, I can't reproduce.

1. Are you using the latest version. I fixed those kind of problems in this commit: https://github.com/Wanchai/FTPbucket/commit/e0a40d21f107d8e159c1a523847946666c722c27 
2. Can you paste the logs in here?

**Comment by jake74** [comment]
Apologies. I downloaded the zip via the 'clone or download' button, and uploaded the files. The problems still existed, so I edited the .htaccess file. Close if this has been addressed.
